- name: install zookeeper                                                                                                                     
  unarchive: src=zookeeper-3.4.6.tar.gz dest=/data/
- name: install configuration file for zookeeper
  template: src=zoo.cfg.j2 dest=/data/zookeeper-3.4.6/conf/zoo.cfg
- name: 建立更新目录
  shell: "[  -d /data/zookeeper-3.4.6/dataDir ] ||  /bin/mkdir /data/zookeeper-3.4.6/dataDir -p"
- name: add myid file
  shell: echo {{ myid }} > /data/zookeeper-3.4.6/dataDir/myid
- name: copy script to clear zookeeper logs.
  copy: src=clean_zklog.sh dest=/data/zookeeper-3.4.6/clean_zklog.sh mode=755
- name: crontab task
  cron: name="clear zk logs" weekday="0" hour="0" minute="0" job="/data/zookeeper-3.4.6/clean_zklog.sh"
- name: start zookeeper
  shell: /data/zookeeper-3.4.6/bin/zkServer.sh start
  tags:
  - start
